### ISSUE TITLE
No such command "make-project"

### ISSUE THREAD

**Issue by mbo42** [Railslide/subvenv#3]
Hi,
Following instructions on git page.

```
(venv)fred10:~/prog/davedb:$ subvenv make-project
Usage: subvenv [OPTIONS] COMMAND [ARGS]...

Error: No such command "make-project"
```
- Just discovered it's because the instructions show a hyphen and it needs an underscore
  
  subvenv make_project

**Comment by Railslide** [comment]
Hi,

thanks for reporting it! I've pushed a fix for it
